### ISSUE TITLE
Github Actions For Public Repos

### ISSUE THREAD

**Issue by hharnisc** [actions/action-builder#1]
In the [creating a new workflow guide](https://developer.github.com/actions/creating-workflows/creating-a-new-workflow/#hello-world-workflow-example) it mentions that workflows can only be created for private repos. 

At Buffer we build most of our products out in the open and this would not allow us to use Actions (not to mention lots of Open Source projects). Is there anything on the roadmap for public repos? 

If it would be helpful I'd love to be involved in making public repo support in Actions a thing.

**Comment by mscoutermarsh** [comment]
@hharnisc Private repos is for the early beta. Public repos are on the roadmap. 😄

**Comment by hharnisc** [comment]
Can't wait :raised_hands: I'll close out this issue :smile:
